v0.45.1 Fixed sidekiq issue NoMethodError   - Fixed a sidekiq issue     An error NoMethodError: undefined method `request_uri' for #<URI::Generic /api/v1/authenticate> was generated     due to the wrong parameter name "otpservice.host"